### ISSUE TITLE
browser issue with geocode

### ISSUE THREAD

**Issue by mguarinello** [northwest-knowledge-network/mdedit#83]
when the user hits the return key on their keyboard while in the geocode input box *say they enter Colorado and then hit return) the editor treats it as some kind of action and highlight some (but not all) of the required fields in red.

**Comment by mguarinello** [comment]
this appears to have been fixed. closing issue

**Comment by mtpain** [comment]
this is still an issue for me on master and on isoURL, reopening.

I get this error in the browser console and no response on the frontend:

<img width="1195" alt="screen shot 2016-02-08 at 8 30 10 pm" src="https://cloud.githubusercontent.com/assets/2425472/12907680/d31e5f06-cea2-11e5-9bb4-dd5f0e2cb26c.png">

**Comment by mguarinello** [comment]
Okay. I see the error in the console now. It no longer pops the user up to the toolbar in the browser as it did before. I will look into this one now.

**Comment by mguarinello** [comment]
fixed with PR #100 
found answer here http://webcheatsheet.com/javascript/disable_enter_key.php
